variables:
#--------------修改点 如果有submodule,请包含该代码
  GIT_SUBMODULE_STRATEGY: normal
#web服务器的发布文件夹名称
#--------------------修改点1-------------------
stages:
  - build
 
build_job:
  stage: build
  tags: 
    - netcore
  script:
    #设置控制台语言为中文,防止乱码
    - chcp 65001
    # 编译
    - dotnet publish
  
    
    - cp src/MaraAgentSystem.Web.Mvc/bin/Debug/netcoreapp2.1/publish /opt/MaraAgentSystem
 
  artifacts:
    paths:
    #--------------------修改点3 路径-------------------
      - "src/MaraAgentSystem.Web.Mvc/bin/Debug/netcoreapp2.1/publish"
    name: "%CI_PROJECT_NAME%_%CI_COMMIT_SHA%"
 

    